name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: { python-version: "3.10" }

    - name: Setup
      run: |
        python -m pip install -U pip
        pip install -U pytest pytest-cov coveralls

    - name: Run tests
      run: |
        pytest --cov --cov-report=term-missing

    - name: Upload coverage to coveralls.io
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
